export const PRODUCTS_FETCH_START = "PRODUCTS_FETCH_START";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL";

export const BRANDS_FETCH_START = "BRANDS_FETCH_START";
export const BRANDS_FETCH_SUCCESS = "BRANDS_FETCH_SUCCESS";
export const BRANDS_FETCH_FAIL = "BRANDS_FETCH_FAIL";

export const CHART_FETCH_START = "CHART_FETCH_START";
export const CHART_FETCH_SUCCESS = "CHART_FETCH_SUCCESS";
export const CHART_FETCH_FAIL = "CHART_FETCH_FAIL";
